# Websocket message constants
# # Status
STATUS = 'status'
STATUS_MESSAGE = 'statusMessage'
STATUS_OK = 'OK'
STATUS_FAIL = 'FAIL'

# # Action
ACTION = 'action'
ACTION_LOG_IN = 'LOG_IN'
ACTION_FETCH_TOP_ADS = 'FETCH_TOP_ADS'
ACTION_PUSH_TOP_ADS = 'PUSH_TOP_ADS'
ACTION_SEARCH_ADS = 'SEARCH_ADS'
ACTION_SAVE_UPDATE_AD = 'SAVE_UPDATE_AD'
ACTION_SAVE_UPDATE_USER = 'SAVE_UPDATE_USER'
ACTION_CHANGE_PASSWORD = 'CHANGE_PASSWORD'
ACTION_RESET_PASSWORD = 'RESET_PASSWORD'
ACTION_FETCH_AD = 'FETCH_AD'
ACTION_PUSH_AD = 'PUSH_AD'

# # Message fields
USERNAME = 'username'
PASSWORD = 'password'
USER_ID = 'userId'
PAYLOAD = 'payload'
SEARCH_PHRASE = 'searchPhrase'
CATEGORY_ID = 'categoryId'
AD_ID = 'adId'
HEADING = 'heading'
TEXT = 'text'
ORGANIZATION_ID = 'organizationId'
IMAGE = 'image'
EMAIL = 'email'

# Django keys
SESSION_SCOPE_USER = 'user'
